### PR TITLE
Added conspicuous messaging that this repo is no longer maintained.

### PR DESCRIPTION
**Pull request by qbunt**
With the thought that someone could actively assume that this repo/generator is being maintained and kept in 'battle-tested' state, I'm adding a message to the readme that shows it as such. I appreciate all the work that's been done here, but it's been stale for a really long time.

### CODE REVIEW

**Comment by trombom** [comment]
I would be in favor of letting people know this is not under active development

@eastridge - this seems to be an accurate statement and rather than have people try it out only to find it outdated should we add the message that @qbunt is proposing?

**Comment by trombom** [comment]
cc @kpdecker

**Comment by kpdecker** [comment]
I don't have commit access to any Walmart projects anymore so I can't merge this. @jasonwebster is maintaining Thorax at this point so he would be a better person to discuss this with.

**Comment by qbunt** [comment]
We can revise the wording or the formatting of that message, but I think everyone gets the concept here. We fell into this generator to find it outdated pretty late in our project, I'd like to avoid others doing the same.

**Comment by qbunt** [comment]
@jasonwebster & @kpdecker let me know if I can help push this along.

**Comment by eastridge** [comment]
@qbunt thanks for the PR

**Comment by qbunt** [comment]
Sure thing, thanks for accepting @eastridge, hope I didn't stomp on too many toes.

**Pull request merged**
